In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv('./heart+disease/processed.cleveland.data', header=None, encoding='unicode_escape')

In [18]:
df.head()

     0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0

In [19]:
df.columns = ['Age', 'Sex', 'Chest-Pain Type', 'Resting Blood Pressure', 'Serum Cholestrol in md/dl',
              'Fasting Blood Sugar > 120mg/dl', 'Resting electrocardiographic results', 'Max Heart Rate', 'Exercise Induced Angina',
              'ST Depression Induced', 'Slope of the peak exercise ST Segment', 'Number of Major Vessels', 'Thal',
              'Diagnosis of Heart Disease']

In [20]:
df.head()

,Age,Sex,Chest-Pain Type,Resting Blood Pressure,Serum Cholestrol in md/dl,Fasting Blood Sugar > 120mg/dl,Resting electrocardiographic results,Max Heart Rate,Exercise Induced Angina,ST Depression Induced,Slope of the peak exercise ST Segment,Number of Major Vessels,Thal,Diagnosis of Heart Disease
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

The columns were renamed to provide more accurate and suggestive column names that give us a clearer picture on the data
that each column contains

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    303 non-null    float64
 1   Sex                                    303 non-null    float64
 2   Chest-Pain Type                        303 non-null    float64
 3   Resting Blood Pressure                 303 non-null    float64
 4   Serum Cholestrol in md/dl              303 non-null    float64
 5   Fasting Blood Sugar > 120mg/dl         303 non-null    float64
 6   Resting electrocardiographic results   303 non-null    float64
 7   Max Heart Rate                         303 non-null    float64
 8   Exercise Induced Angina                303 non-null    float64
 9   ST Depression Induced                  303 non-null    float64
 10  Slope of the peak exercise ST Segment  303 non-null    float64
 11  Number of Major Vessels                303 non-null    object
 12  Thal                                   303 non-null    object
 13  Diagnosis of Heart Disease             303 non-null    int64
dtypes: float64(11), int64(1), object(2)
memory usage: 33.3+ KB

We have 13 columns with data types ranging from floats to objects to integers, most of the data are floats followed by objects then integers.
This is slightly weitd as both columns 11 and 12 are floats but have been converted to objects, possibly due to null values '?' being read as a string and pandas not being able to classify them as floats. This will have to be a consideration later on when classifying and normalizing the data for MEG use.

In [22]:
df.describe()

,Age,Sex,Chest-Pain Type,Resting Blood Pressure,Serum Cholestrol in md/dl,Fasting Blood Sugar > 120mg/dl,Resting electrocardiographic results,Max Heart Rate,Exercise Induced Angina,ST Depression Induced,Slope of the peak exercise ST Segment,Diagnosis of Heart Disease
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000

Before any data cleaning, we can see that the mean in each colulmn varies greatly, which may cause difficulties later on for our machine learning model, hence this data will need to be cleaned later. No obvious anomalies are visible

In [23]:
df.isnull().sum()

Age                                      0
Sex                                      0
Chest-Pain Type                          0
Resting Blood Pressure                   0
Serum Cholestrol in md/dl                0
Fasting Blood Sugar > 120mg/dl           0
Resting electrocardiographic results     0
Max Heart Rate                           0
Exercise Induced Angina                  0
ST Depression Induced                    0
Slope of the peak exercise ST Segment    0
Number of Major Vessels                  0
Thal                                     0
Diagnosis of Heart Disease               0
dtype: int64

There aren't any null values in any of the columns. However I suspect this might be because the UCI dataset notoriously uses '?' as its missing value marker and not a proper null.

In [24]:
df = df.replace('?', np.nan)
df.isnull().sum()

Age                                      0
Sex                                      0
Chest-Pain Type                          0
Resting Blood Pressure                   0
Serum Cholestrol in md/dl                0
Fasting Blood Sugar > 120mg/dl           0
Resting electrocardiographic results     0
Max Heart Rate                           0
Exercise Induced Angina                  0
ST Depression Induced                    0
Slope of the peak exercise ST Segment    0
Number of Major Vessels                  4
Thal                                     2
Diagnosis of Heart Disease               0
dtype: int64

Here we see the null values that we have to replace later on in two columns: Number of Major Vessels and Thal.

Our label column is the "Diagnosis of Heart Disease" column. The values we have fall under a range(0 - 4) while the data we feed the machine learning model (MEG) should be binary so this is something to consider while cleaning the data

Stopped here — need to investigate the Diagnosis of Heart Disease column values and decide how to handle it before ETL cleaning

In [27]:
df['Diagnosis of Heart Disease'].value_counts()

Diagnosis of Heart Disease
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

Now we begin the process of transforming the data so that it is suitable for our ML model.
1) We have two columns with object values that need to be converted into floats, these are also our columns with null values
   a) Handle the null values (Replace dont drop since we don't have a lot of data to begin with)
   b) Convert the column into floating point values

2) Fix the target column

   a) We need a binary target column as we want to flag a patient as at-risk or not. 0 stays as 0 and 1-4 are classified as 1.
3) Handle categorical columns

   a)We have columns like chest pain, rated from 1 - 4, the model may misinterpret this as 4 being 4 times as great as 1 when in fact we have different chest pain types not specifically a rating of chest pain. This can be handled through one hot encoding

4) Normalise the numeric columns

   a) We have values in some columns ranging from 0 - 272 while in others the max value is only 4. This can heavily skew and dominate the data hence we should normalise the data and keep it in a range of 0 - 1 for all the columns.

Determining which columns are continuous and categorical, we only normalise the continuous data and one-hot encode the categorical one

To normalise: Age, Resting blood pressure, serum cholestrol, max heart rate, diagnosis of heart disease, ST Depression induced
To encode: Chest pain type, resting ECG, Number of major vessels, Tha, slope of the peak

Nothing to do: Sex, Fasting blood sugar, exercise Induced Angina